package:
  name: plink2
  version: "2.00a2.3"

build:
  number: 1

source:
  url: https://github.com/chrchang/plink-ng/archive/v2.00a2.3.tar.gz
  sha256: 4a9e9ff670967f9766bcd5571d028ed6c04bc8f07781eac1b95366748544df77

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - openblas # [not osx]
  run:
    - openblas # [not osx]

test:
  commands:
    - plink2 --help | grep "PLINK v2.00a2.3"

about:
  home: https://www.cog-genomics.org/plink2
  license: GPL
  license_file: LICENSE
  summary: Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
