package:
  name: chainmap
  version: "1.0.3"

source:
  url: https://files.pythonhosted.org/packages/c7/ab/268a15383b75ca3e58ce344bce165b79768e516f8e79c87cbdaba30c38e9/chainmap-1.0.3.tar.gz
  sha256: e42aaa4b3e2f66102a11bfd563069704bfbfd84fdcb517b564effd736bf53cd9

build:
  # Skip builds since it is most likely not needed for Python 3.
  # Before enabling those builds, rather consider to move the package to conda-forge.
  skip: True # [py3k]
  number: 0

requirements:
  host:
    - python >=2.7,<3
    - setuptools

  run:
    - python >=2.7,<3

test:
  imports:
    - chainmap

about:
  home: https://bitbucket.org/jeunice/chainmap
  license: Python Software Foundation License
  summary: 'Backport/clone of ChainMap for py26, py32, and pypy3.'
