package:
  name: scvis
  version: "0.1.0"

source:
  url: https://bitbucket.org/jerry00/get/af73849.tar.gz
  sha256: 7b6267b6bf3bd3a944ce869cbd7f83b96d67f0047678a9a5581c46ea24635d90
  git_rev: master

build:
  noarch: python
  number: 0
  string: scvis

requirements:
  run:
      - python
      - setuptools
      - tensorflow >=1.1
      - pyYAML >=3.11
      - matplotlib >=1.5.1
      - numpy >=1.11.1
      - pandas >=0.19.1
      - nomkl
  host:
      - python

test:
  commands:
    - scvis -h
    - scvis train -h
    - scvis map -h

about:
  home: https://bitbucket.org/jerry00/scvis-dev/commits/all
  license: Creative Commons Attribution 4.0 International License
  lisence_file: LICENSE
  summary: scvis is a python package for dimension reduction of high-dimensional biological data, especially single-cell RNA-sequencing (scRNA-seq) data.
