package:
  name: scvis
  version: "0.1.1"

source:
  url: https://github.com/shahcompbio/scvis/tarball/af73849679e8f84d80e4418d0badf5ea9d9a87af
  sha256: b56b695eefeaff33f95fcfa25ab6069b52660c00329542188ab65c5b3c2d8dc1
  git_rev: master

build:
  noarch: python
  number: 0
  string: scvis

requirements:
  run:
      - python
      - setuptools
      - tensorflow >=1.13
      - pyYAML >=3.11
      - matplotlib >=1.5.1
      - numpy >=1.11.1
      - pandas >=0.19.1
      - nomkl
      - pip
      - wheel
  host:
      - python
      - pip

about:
  home: https://github.com/shahcompbio/scvis
  license: Creative Commons Attribution 4.0 International License
  license_file: LICENCE
  summary: scvis is a python package for dimension reduction of high-dimensional biological data, especially single-cell RNA-sequencing (scRNA-seq) data.

extra:
  skip-lints:
    - missing_tests  # conda-forge::tensorflow requires GLIBC >=2.16
                     #See https://github.com/conda-forge/tensorflow-feedstock/issues/67
  notes: conda-forge::tensorflow requires GLIBC >=2.16. It should be present on most, but not all systems. See https://github.com/conda-forge/tensorflow-feedstock/issues/67
