{% set version = "1.0" %}

package:
  name: trimns_vgp
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  git_url: https://github.com/VGP/vgp-assembly.git
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

requirements:
  host:
    - python <3.8
  run:
    - python =<3.8
    - biopython =<1.77

test:
  commands:
    - which clip_regions_DNAnexus.py
    - which remove_fake_cut_sites_DNAnexus.py
    - which trim_Ns_DNAnexus.py

about:
    home: https://github.com/VGP/vgp-assembly
    license: BSD-3
    license_file: license
    summary: TrimNs is used to trim and remove fake cut sites from bionano hybrid scaffold data in the VGP pipeline.