package:
  name: "plink"
  version: "1.90b6.18"

build:
  number: 0

source:
  url: http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20200616.zip # [linux]
  sha256: 99735807772d3259623e3809941e15585ed8e4b3d4cb2845c2780ef4bb3d33a6 # [linux]
  url: http://s3.amazonaws.com/plink1-assets/plink_mac_20200616.zip # [osx]
  sha256: 4ec88bba5b666998f1108fdeb671b655ac7df6612fddef8524cd2df18e2e47f1 # [osx]
  url: http://s3.amazonaws.com/plink1-assets/plink_win64_20200616.zip # [osw]
  sha256: 0244d3e441e46d16b17d1c57815b000326e49183a7c61dcde94f1e48761e9e6a # [osw]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - openblas # [not osx]
  run:
    - openblas # [not osx]

test:
  commands:
    - plink --help

about:
  home: https://www.cog-genomics.org/plink2
  license: GPL
  license_file: LICENSE
  summary: Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
