package:
    name: r-cerebroprepare
    version: 1.0.0

source:
    git_url: https://github.com/romanhaa/cerebroPrepare.git

build:
    number: 0

rpaths:
    - lib/R/lib/
    - lib/

requirements:
    run:
        - r-base
        - r-rcpp
        - r-biocmanager >=1.30.4
        - bioconductor-biomart >=2.38.0
        - r-dplyr >=0.7.8
        - r-future.apply >=1.1.0
        - r-httr >=1.4.0
        - r-matrix >=1.2
        - r-pbapply >=1.4
        - r-readr >=1.3.1
        - r-seurat >=2.3.0
        - r-tidyr >=0.8.2

    host:
        - r-base
        - r-rcpp
        - r-biocmanager >=1.30.4
        - bioconductor-biomart >=2.38.0
        - r-dplyr >=0.7.8
        - r-future.apply >=1.1.0
        - r-httr >=1.4.0
        - r-matrix >=1.2
        - r-pbapply >=1.4
        - r-readr >=1.3.1
        - r-seurat >=2.3.0
        - r-tidyr >=0.8.2

test:
    commands:
        - $R -e "library(cerebroPrepare); help("getEnrichedPathways")"

about:
    home: https://github.com/romanhaa/cerebroPrepare
    license: MIT
    summary: An R wrapper for cerebroPrepare
    description: |
        An R wrapper for cerebroPrepare, the tool used convert data from Seurat objects
        into cerebro objects, cabaple of being examined in the cerebro application.
        See <https://github.com/romanhaa/Cerebro> for information regarding the application.
        See <https://www.biorxiv.org/content/10.1101/631705v1> for initial publication of the
        tool.

extra:
    recipe-maintainters:
        - aostrovsky01
